#!/bin/bash

#echo "Generating tags and cscope database..."
SECONDS=0
#CTAGS_FLAG=--extra=+f
#CTAGS_FLAG="--fields=+niazS --extra=+fq --c++-kinds=+px --c-kinds=+px --output-format=e-ctags"
CTAGS_FLAG="--fields=+niazS --extra=+fq --c++-kinds=+px --c-kinds=+px --output-format=e-ctags"
FLIST="./.cscope.files"

# Rebuild one file: used by auto update tag come from vim
#   - file should be full-path
if [ ! -z "$1" ]; then
	rm -f .tags 2> /dev/null
	rm -f .tagx 2> /dev/null
	rm -f GTAGS 2> /dev/null
	rm -f GPATH 2> /dev/null
	rm -f GRTAGS 2> /dev/null
	rm -f tags 2> /dev/null
	rm -f tagx 2> /dev/null
	rm -f tags.lock 2> /dev/null
	rm -f tags.temp 2> /dev/null
	rm -f cscope.* 2> /dev/null
	rm -f ${FLIST} 2> /dev/null
	rm -fr .tagme 2> /dev/null
	rm -fr .ccls-cache 2> /dev/null
	exit 0

	if [ -f ./.tags ] && [ -f $1 ]; then
		# only rebuild tags when the file belong curr dir
		#if [[ "$1" == "$PWD/"* ]]; then
			file=$1
			pwdlen=${#PWD}
			LC_COLLATE=C ctags ${CTAGS_FLAG} -f .tags -a "./${file:$pwdlen}"
			#duration=$SECONDS
			#notify-send "Done tags R $(($duration / 60)):$(($duration % 60))."
		#fi
		exit 0
	fi
fi

# Rebuild All
mkdir -p ./.tagme

if [ -f ${FLIST} ]; then
	filecnt_c=1024
else
	filecnt_c=$(find . -maxdepth 3 -type f -name '*.c' | wc -l)
fi

if [ $filecnt_c -ge 1 ]; then
	if [ ! -z "$1" ]; then
		tagscope=$1
	else
		tagscope="default"
	fi

	case "$tagscope" in
	   "all")
		   echo "tag all"
		   find -L . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ./.tagme/cscope.f1
	   ;;
	   "wad")
		   echo "tag wad"
		   find daemon/wad -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ./.tagme/cscope.f1
	   ;;
	   *)
		   echo "tag default"
		   find . -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' > ./.tagme/cscope.f1
	   ;;
	esac

	wad_c=$(grep 'daemon/wad' ./.tagme/cscope.f1 | wc -l)
	if [ $wad_c -ge 10 ]; then
		cat ./.tagme/cscope.f1             | \
			grep -v 'ccls-cache/'          | \
			grep -v 'wad/ui/stdin/'        | \
			grep -v 'wad/redirect/socket/' | \
			grep -v 'wad/test/'            | \
			grep -v 'wad/cache/test/'      | \
			grep -v 'daemon/sslvpnd/'      | \
			grep -v 'daemon/waagent/'      | \
			grep -v 'linux/'               | \
			grep -v 'linux-.*/'            | \
			grep -v 'compress/'            | \
			grep -v 'cooked/'              | \
			grep -v 'fortitest/'           | \
			grep -v 'linuxatm/'            | \
			grep -v 'sysctl/'              | \
			grep -v 'router/'              | \
			grep -v 'fortiweb/'            | \
			grep -v 'fortitest/'           | \
			grep -v 'tests/gtest/'         | \
			grep -v 'tests/'               | \
			grep -v 'tools/'               | \
			grep -v '/_' \
			> ./.tagme/cscope.f2
	else
		cat ./.tagme/cscope.f1             | \
			grep -v 'ccls-cache/'          | \
			grep -v '/_' \
			> ./.tagme/cscope.f2
	fi

	sort ./.tagme/cscope.f2 > ./.tagme/cscope.f3
	mv ./.tagme/cscope.f3 ${FLIST}
	#    /usr/bin/time gtags -f ${FLIST}
	#    /usr/bin/time global -u -L ${FLIST}
	rm -f .tags 2> /dev/null
	rm -f .tagx 2> /dev/null

	# tage-emacs, tags-vim, tagx-fuzzy
	#LC_COLLATE=C ctags -e ${CTAGS_FLAG} -L ${FLIST} -f .tage > /dev/null 2>&1
	LC_COLLATE=C ctags ${CTAGS_FLAG} -L ${FLIST} -f .tags > /dev/null 2>&1
	LC_COLLATE=C ctags -xL ${FLIST} > .tagx 2>/dev/null

	cscope -kbq -i ${FLIST} > /dev/null 2>&1
	ccls --index=. --init='{"clang":{"extraArgs": ["-fms-extensions", "-Wno-microsoft-anon-tag", "-Wno-microsoft", "-Wno-gnu-anonymous-struct"]}}' > /dev/null 2>&1

	duration=$SECONDS
	notify-send "Done tags files $(($duration / 60)):$(($duration % 60))."
else
	rm -f .tags 2> /dev/null
	rm -f .tagx 2> /dev/null

	# tage-emacs, tags-vim, tagx-fuzzy
	#LC_COLLATE=C ctags -e ${CTAGS_FLAG} -f .tage -R . > /dev/null 2>&1
	LC_COLLATE=C ctags ${CTAGS_FLAG} -f .tags  --exclude=.git --exclude=node_modules --exclude=.ccls-cache -R . > /dev/null 2>&1
	LC_COLLATE=C ctags --exclude=.git --exclude=node_modules --exclude=.ccls-cache -xR . > .tagx 2>/dev/null

	cscope -bcqR > /dev/null 2>&1
	#ccls --index=. --init='{"clang":{"extraArgs": ["-fms-extensions", "-Wno-microsoft-anon-tag", "-Wno-gnu-anonymous-struct", "--gcc-toolchain=/usr"]}}' > /dev/null 2>&1
	ccls --index=. --init='{"clang":{"extraArgs": ["-fms-extensions", "-Wno-microsoft-anon-tag", "-Wno-microsoft", "-Wno-gnu-anonymous-struct"]}}' > /dev/null 2>&1

	duration=$SECONDS
	notify-send "Done tags R $(($duration / 60)):$(($duration % 60))."
fi

#ctags -e --c-kinds=+defgstum -L ${FLIST} > /dev/null 2>&1
rm -fr ./.tagme

